// react/my-first-react-app/src/product-list/ProductList.jsx
import React from 'react';
import './ProductList.css'

function ProductList(props) {
    const productList = props.products.map(product => {
        return (
            <li key={product.id}>
                <h2>{product.name}</h2>
                <img src={product.image} alt={product.name} />
                <p>{product.description.length > 150 ? product.description.slice(0, 150) + '...' : product.description}</p>
                <div className="price">{product.price} €</div>
                <div>
                    <button className="button">add to cart</button>
                </div>
            </li>
        );
    });

    return (
        <div className="wrapper">
            <h1>Products</h1>
            <div className="views">
                <i className="material-icons">
                    view_list
               </i>
                <i className="material-icons">
                    view_module
              </i>
            </div>
            <ul>
                {productList}
            </ul>
        </div>
    );
}

export default ProductList;

// my-first-angular-app/src/app/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { products } from '../mock-products';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.scss']
})
export class ProductListComponent implements OnInit {

  products = products;
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="wrapper">
  <h1>Products</h1>

  <i class="material-icons">
    view_list
  </i>
  <i class="material-icons">
    view_module
  </i>

  <ul class="products">
    <li *ngFor="let product of products" class="product">
      <img src="{{product.image}}" alt="The imgae product is: {{product.name}}">
      <div>
        <h2>{{product.name}}</h2>
        <p>{{product.description}}</p>
        <div class="price">{{product.price}} €</div>
      </div>
    </li> <!-- .product -->
  </ul> <!-- .products -->
</div> <!-- .wrapper -->
